### ISSUE TITLE
Raspirobotboard3 running motors

### ISSUE THREAD

**Issue by philpeace** [simonmonk/raspirobotboard3#5]
Hi,

I'm running one of your Raspirobotboards on a PI2 B+ and am having problems with it outputing enough volts to drive my motor. I have a 9V battery attached and when I use `rr = RRB3(9, 3)` the maximum voltage I can get seems to be about 1.5V. The motors I'm using are the standard yellow 3V ones the same as in the photo in your README.

As far as I can tell I have followed your instructions, but do you have any suggestions?

Thanks

**Comment by simonmonk** [comment]
I'm guessing that you are using rr.forward without setting the speed. By
default, the speed is 50% (0.5) so you probably need to set the speed to
1.0.

Si.

On 28 February 2016 at 22:00, Phil <notifications@github.com> wrote:

> Hi,
>
> I'm running one of your Raspirobotboards on a PI2 B+ and am having
> problems with it outputing enough volts to drive my motor. I have a 9V
> battery attached and when I use rr = RRB3(9, 3) the maximum voltage I can
> get seems to be about 1.5V. The motors I'm using are the standard yellow 3V
> ones the same as in the photo in your README.
>
> As far as I can tell I have followed your instructions, but do you have
> any suggestions?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simonmonk/raspirobotboard3/issues/5>.
>



-- 
--
http://simonmonk.org
@simonmonk2

**Comment by philpeace** [comment]
Thanks. Silly mistake by me, I was wiring up the motors wrong. After seeing how it's done here http://www.monkmakes.com/rrb3/ I can see where I went wrong.
